In [27]:
import csv
import numpy as np
import pandas as pd

# Cargar el archivo .txt
df = pd.read_csv('datosVino.txt', delimiter='\t')

# Guardar el DataFrame como un archivo CSV
df.to_csv('datos.csv', index=False)
print("Archivo CSV creado exitosamente.")

# Calcular medias
df = pd.read_csv('datos.csv')
medias = df.mean()

# Mostrar las medias
print("Medias de cada columna:\n", medias)


# Calcular matriz de varianzas y covarianzas
matriz_covarianzas = np.cov(data2, rowvar=False)
print("Matriz de varianzas y covarianzas:\n", matriz_covarianzas)

autovalores, autovectores = np.linalg.eig(matriz_covarianzas)
print("Los autovalores son:")
print(autovalores)

Varianza_total = sum(autovalores)
print("La varianza total es:")
print(round(Varianza_total,2))

Porcentaje_Varianza1 = autovalores[0]/Varianza_total
print(f"El porcentaje de varianza explicado por el primer componente principal es: {Porcentaje_Varianza1*100:.2f}%")

Porcentaje_Varianza2 = autovalores[1]/Varianza_total
print(f"El porcentaje de varianza explicado por el segundo componente principal es: {Porcentaje_Varianza2*100:.2f}%")

Porcentaje_Varianza3 = autovalores[2]/Varianza_total
print(f"El porcentaje de varianza explicado por el tercer componente principal es: {Porcentaje_Varianza3*100:.2f}%")

Porcentaje_Varianza4 = autovalores[3]/Varianza_total
print(f"El porcentaje de varianza explicado por el cuarto componente principal es: {Porcentaje_Varianza4*100:.2f}%")

Porcentaje_Varianza5 = autovalores[4]/Varianza_total
print(f"El porcentaje de varianza explicado por el quinto componente principal es: {Porcentaje_Varianza5*100:.2f}%")

Y11 = np.dot(autovectores[:,0], data2[0][0:5])
Y21 = np.dot(autovectores[:,1], data2[0][0:5])
Y31 = np.dot(autovectores[:,2], data2[0][0:5])
print(f"El valor Y11 es: {Y11:.2f}")
print(f"El valor Y21 es: {Y21:.2f}")
print(f"El valor Y31 es: {Y31:.2f}")

Y12 = np.dot(autovectores[:,0], data2[1][0:5])
Y22 = np.dot(autovectores[:,1], data2[1][0:5])
Y32 = np.dot(autovectores[:,2], data2[1][0:5])
print(f"El valor Y12 es: {Y12:.2f}")
print(f"El valor Y22 es: {Y22:.2f}")
print(f"El valor Y32 es: {Y32:.2f}")


Archivo CSV creado exitosamente.
Medias de cada columna:
 calidad    12.442105
aroma       4.847368
cuerpo      4.684211
sabor       4.768421
fuerza      4.255263
dtype: float64
Matriz de varianzas y covarianzas:
 [[ 4.14196302  1.56416785  0.91960171  1.65109531 -0.0729303 ]
 [ 1.56416785  1.17174964  0.48968706  0.81964438  0.16109531]
 [ 0.91960171  0.48968706  0.67920341  0.54786629  0.09251778]
 [ 1.65109531  0.81964438  0.54786629  1.05681366  0.13638691]
 [-0.0729303   0.16109531  0.09251778  0.13638691  0.54470128]]
Los autovalores son:
[5.83179043 0.8061156  0.218033   0.3457107  0.39278129]
La varianza total es:
7.59
El porcentaje de varianza explicado por el primer componente principal es: 76.79%
El porcentaje de varianza explicado por el segundo componente principal es: 10.61%
El porcentaje de varianza explicado por el tercer componente principal es: 2.87%
El porcentaje de varianza explicado por el cuarto componente principal es: 4.55%
El porcentaje de varianza explicado po